<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TrustLab.Domain\TrustLab.Domain.csproj" />
    <ProjectReference Include="..\TrustLab.Application\TrustLab.Application.csproj" />
    <ProjectReference Include="..\TrustLab.Rag\TrustLab.Rag.csproj" />
    <ProjectReference Include="..\TrustLab.Guardrails\TrustLab.Guardrails.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
